---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3
  labels:
    app: test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test3
    spec:
      containers:
        - name: test3
          image: test3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 1Gi
            limits:
              memory: 1Gi
