logging:
  level.root: WARN
  level.no.fdk: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info

url:
  fellesdatakatalog:
    api: ${RESOURCE_SERVICE_URI}
    frontend: ${FDK_URI}
  kudaf:
    soknadApi: https://frontend-soknad-api.paas2.uninett.no

application:
  cors:
    originPatterns: ${CORS_ORIGIN_PATTERNS}

---
spring:
  config.activate.on-profile: dev

logging:
  level.no.digdir.accessrequestapi: DEBUG

url:
  fellesdatakatalog.api: https://resource.api.staging.fellesdatakatalog.digdir.no
  fellesdatakatalog.frontend: https://staging.fellesdatakatalog.digdir.no

application:
  cors:
    originPatterns: localhost:3001

---
spring:
  config.activate.on-profile: test
