---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base/example-app
  - example-app-ingress.yaml

patchesStrategicMerge:
  - example-app-env.yaml
