---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: halvor
  labels:
    app: halvor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halvor
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: halvor
    spec:
      containers:
        - name: halvor
          image: halvor
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 350Mi
            limits:
              memory: 350Mi
