---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: halvor
    newName: ghcr.io/hackathon-autoharvest/halvor
    newTag: $(GIT_COMMIT_SHA)
