---
apiVersion: v1
kind: Service
metadata:
  name: halvor
  annotations:
    cloud.google.com/backend-config: '{"default": "backendconfig"}'
spec:
  selector:
    app: halvor
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
