---
apiVersion: v1
kind: Service
metadata:
  name: example-app #TODO: Change to your app name
spec:
  selector:
    app: example-app #TODO: Change to your app name
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
