---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hackathon
resources:
  - ../../base/test4
  - ingress.yaml

patchesStrategicMerge:
  - env.yaml

#secretGenerator:
#  - name: example-app-secret
#    literals:
#      - DB_PASSWORD=$(DB_PASSWORD)
#      - API_KEY=$(API_KEY)
#    type: Opaque
