---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app #TODO: Change to your app name
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ingress-static-ip"
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-app #TODO: Change to your app name
                port:
                  number: 8080
