---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: halvor
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: halvor
                port:
                  number: 8080
