---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: halvor
spec:
  ingressClassName: gce
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: halvor
                port:
                  number: 8080
