---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: samferdselsdata
spec:
  rules:
    - host: ""
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: samferdselsdata
                port:
                  number: 8080
