---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hackathon
resources:
  - ../base
  - ingress.yaml

patchesStrategicMerge:
  - env.yaml

secretGenerator:
  - name: example-app-secret
    files:
      - secrets.env # File containing key-value pairs (excluded from repository)
    type: Opaque
