---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - example-app-deployment.yaml
  - example-app-service.yaml
images:
  - name: example-app
    newName: eu.gcr.io/digdir-fdk-infra/example-app
    newTag: $(GIT_COMMIT_SHA)
