---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: test4
    newName: ghcr.io/fellesdatakatalog/hackathon-autoharvest/test4
    newTag: $(GIT_COMMIT_SHA)
