name: Deploy

on:
  push:
    branches:
      - <my-branch>

jobs:
  build:
    name: Build affected apps when pull request is created
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: <app-name>
      environment: hackathon
      cache_path: ./dist
      cache_key: cache-dist-${{ github.sha }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}

  deploy:
    name: Deploy affected apps to staging environment with reusable workflow
    needs: build
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: <app-name>
      environment: hackathon
      cluster: digdir-fdk-hackathon
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.HACKATHON_DEPLOY_SA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
